dist: trusty
sudo: true
language: cpp
compiler: clang++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - lcov

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  
  
  - sudo apt-get install -qq g++-7
  - sudo update-alternatives --install /user/bin/g++ g++ /user/bin/g++-7 90

script:
  - make
  - ./unit-test

after_success:

notifications:
  email: false
